version: '3.9'

services:
  api:
    build: .
    container_name: face_recognition_api
    volumes:
      - ./src:/app/src
      - ./faces_db:/app/faces_db
    env_file:
      - .env
    ports:
      - "8000:8000"

volumes:
  pgdata:
